### ISSUE TITLE
How exactly is Pearl "Production-ready"?

### ISSUE THREAD

**Issue by ogencoglu** [facebookresearch/Pearl#100]
How exactly is Pearl "Production-ready" when dependency versions are missing, there is no pip package on pypi, documentation is thin, does not support python versions that have been around for several years?

**Comment by rodrigodesalvobraz** [comment]
The production-readiness of Pearl is emphasized in the modularity to deal with real world challenges and its versatility in addressing and optimizing many problems we’ve seen in production. Please check [Pearl's paper](https://arxiv.org/abs/2312.03814) for more details on that.

Thanks for pointing out some of the issues. Pearl should easily run on more recent Python versions, and users could even modify that themselves. In any case, we will update that in its config files (same for dependency versions). We will improve documentation in the next months, and make it available on PyPI.

In spite of those issues, the system itself is indeed something can and is used in production.
