### ISSUE TITLE
[Feature] Conservative Q-Learning

### ISSUE THREAD

**Issue by cvnad1** [facebookresearch/Pearl#105]
Hello,

I have seen many versions of Q-learning implemented in Pearl, but I would like to add the conservative Q-learning algorithm which is quite a milestone.

https://arxiv.org/abs/2006.04779

**Comment by rodrigodesalvobraz** [comment]
Hi @cvnad1,

Conservative learning is already [available as an option](https://github.com/facebookresearch/Pearl/blob/705f0a85ca63a24c2a1dec7f820121c5386af5bd/pearl/policy_learners/sequential_decision_making/deep_q_learning.py#L52) in the Deep Q-learning policy learner (in fact, it's an option of its parent class, Deep`TDLearning`).

Hope that helps.
