### ISSUE TITLE
[Question] Offline evals

### ISSUE THREAD

**Issue by igorcosta** [facebookresearch/Pearl#11]
Given that offline evaluations and model-based RL methods are planned for the next version.

Could you share here some of the challenges that made the those features being deferred since safe learning is part of the unique way?

Would be keen to know more.

**Comment by BillMatrix** [comment]
Great question! Offline eval or Off-policy policy evaluation is actually a painpoint many RL practitioners go through. However, for long-horizon stochastic environment tasks, OPE in general blows up in its variance in estimate, hence not super trustworthy. However, we are working towards providing support, which can help some users' use cases, but we don't expect that to be a major thing for most users using Pearl. Similarly for model based learning, it doesn't in general work very well when you have a huge action space as well as highly stochastic environment, hence we didn't prioritize that in this round of feature support but will try to provide support for the popular methods in the field and provide tutorials on how that can be combined with our current architecture in the future.
