### ISSUE TITLE
Is this Q*?

### ISSUE THREAD

**Issue by fakerybakery** [facebookresearch/Pearl#12]
Hi,
Is this basically Q*?

**Comment by rodrigodesalvobraz** [comment]
Yes. But please don't tell anyone.

**Comment by fakerybakery** [comment]
Haha 🤣 - but are the principles similar?

**Comment by rodrigodesalvobraz** [comment]
We don't know what Q* really is, but it seems to be related to sequential decision making, which is also what Pearl and RL in general do. But this is just a vague, abstract similarity.

**Comment by BillMatrix** [comment]
@fakerybakery thanks for reaching out! Like what @rodrigodesalvobraz said, we don’t exactly know what Q* is but I would suspect it is a combination of multiple RL features, likely some model free + model based learning approach. We have most of the popular model-free support on a lot of different dimensions of an RL agent and we are working towards supporting the same for model-based approaches.

Pearl’s capability of combining multiple RL features/capabilities in a single agent will help build intelligent agents that are more capable than  what they are able to do today. We hope that Pearl will incubate more powerful AI agents than these built by the mysterious Q* algorithm.

**Comment by fakerybakery** [comment]
Thank you for the detailed explanation!
