### ISSUE TITLE
Multi-agent Reinforcement Learning?

### ISSUE THREAD

**Issue by paapu88** [facebookresearch/Pearl#28]
Dear Developers,
Is multi-agent Reinforcement Learning possible with Pearl
or should one go for https://marllib.readthedocs.io/en/latest/ ?
Terveisin, Markus

**Comment by rodrigodesalvobraz** [comment]
Sorry, Pearl was not designed with multi-agent RL in mind. It might be possible to do it with some redesign (or implementing a `PearlAgent` that plays the role of multiple agents), but this would not be trivial or immediate.
