### ISSUE TITLE
Demo DQN-LSTM dose not converge

### ISSUE THREAD

**Issue by JunYao0619** [facebookresearch/Pearl#34]
I run the demo file in https://github.com/facebookresearch/Pearl/tree/main/pearl/tutorials/single_item_recommender_system_example/demo.ipynb, the result of DQN+LSTM did not converge as the tutorial claims. The codes are exactly the same as in the demo.

![image](https://github.com/facebookresearch/Pearl/assets/137016056/a703bf92-2943-49fc-bf70-18e24624dd15)

**Comment by BillMatrix** [comment]
We'll look into this in the new year. Stay tuned.

**Comment by nv78** [comment]
cool

**Comment by yiwan-rl** [comment]
Thanks for pointing this out. It seems that the env.py file was not the correct version. We have already corrected it. When you run the code again, you should see a result similar to the figure below:

![output](https://github.com/facebookresearch/Pearl/assets/14853238/eac24492-aafa-4a94-9877-63fcb32494cb)
