### ISSUE TITLE
Recommender System Example

### ISSUE THREAD

**Issue by mehrdad78** [facebookresearch/Pearl#35]
Hi there.
My Question is about Recommender system example you provided.
1.what does it actually do? Really i can not understand .
2. what is exactly these two: i mean **env_model_state_dict.pt** and **news_embedding_small.pt**
   `model.load_state_dict(torch.load("Pearl/pearl/tutorials/single_item_recommender_system_example/**env_model_state_dict.pt**"))
actions = torch.load("Pearl/pearl/tutorials/single_item_recommender_system_example/**news_embedding_small.pt**")`
 finally i need some more example to know how to use the Pearl!

**Comment by BillMatrix** [comment]
Hi there, sorry about the late reply. We all just came back from the holiday break.

env_model_state_dict.pt is a pre-trained model that predicts user's behavior given a history of news impressions and news_embedding_small.pt is a set news representations. Both are coming from the MIND dataset. 

More tutorials will come Q1 this year.
