### ISSUE TITLE
How to infer result of the tutorials?

### ISSUE THREAD

**Issue by Souptik-lilly** [facebookresearch/Pearl#41]
How the infer the results from mind dataset in the tutorial provided, once the agent is trained? Is there a test set available? Once the agent is trained, agent.act() returns either 0/1 . What does it signify?

**Comment by BillMatrix** [comment]
In our tutorial, to make training complete in a short period of time, we only offered the agent two possible recommendations as available action space. Each action is represented by a 100-dimensional vector. To see what these actions are, you can print out the action_results object and you'll see the next available set of recommendations in representations. 0/1 are indices to which recommendation the agent chooses. 

In general you can extend this by modifying the env.py file on your end to make it a bigger set of recommendations per step.
