### ISSUE TITLE
online_learning function meet custom gym env without register 

### ISSUE THREAD

**Issue by jzxhi31** [facebookresearch/Pearl#42]
`info = online_learning(
    agent = agent,
    env = env,
    number_of_steps = number_of_steps,
    **print_every_x_steps=1000,**
    record_period = record_period,
    learn_after_episode= True
)`

cause:

File "/workspace/Pearl/pearl/utils/instantiations/environments/gym_environment.py", line 169, in __str__
    return self.env.spec.id
AttributeError: 'NoneType' object has no attribute 'id'

reason: gym env spec is none before register.

**Comment by rodrigodesalvobraz** [comment]
Imported the PR; being reviewed, should be published soon.
