### ISSUE TITLE
What is the policy of Pull Requests ?

### ISSUE THREAD

**Issue by cryptexis** [facebookresearch/Pearl#62]
I am a bit confused - yesterday I made a #61   which was small enough to be merged not to disrupt any other functionality. @rodrigodesalvobraz has recognised the issue, however PR was closed. And to point out that the issue still persists on the main branch. Meaning, the tutorial on CBs are going to fail.

I am not taking it personally, just want to understand if this is a truly open source project where people are free to contribute
OR 
it is governed by Metas internal policies and we just have to report issues and wait until the development team will address them?

**Comment by cryptexis** [comment]
ok to be fair now it is merged. Still please explain the process. Thanks!

**Comment by rodrigodesalvobraz** [comment]
Sure, I am glad to explain. There is an internal Meta repository that is the "source of truth" for the project. The GitHub repository is generated *from* the internal Meta repository. So we don't merge GitHub PRs directly to the GitHub repository -- they must first be imported into internal Meta repository. When Meta employees look at the GitHub PR, there is a special button visible only to them that executes that import. The changes are then automatically reflected from internal Meta repository back to GitHub. This is why you don't see your PR having being directly merged, but you still see your changes in the repository.

I will include this explanation to the `CONTRIBUTING` page so others are aware.

Hope that helps, glad to answer other questions.
