### ISSUE TITLE
Frozen-lake tutorial

### ISSUE THREAD

**Issue by mehrdad78** [facebookresearch/Pearl#64]
Hi there!
My question is about the plot you shown in frozen-lake example.
What does it show to us?
How can we understand that the problem is solved?
![image](https://github.com/facebookresearch/Pearl/assets/46048846/118d7b03-b1b6-4c28-962d-0353dd1a352c)

**Comment by hongjun7** [comment]
Hello, @mehrdad78.
As the number of `steps` increases, we can observe an increase in the average `return` value.
Furthermore, starting from around 10,000 steps, the `return` value consistently stabilizes around 1.
This indicates that the model has been successfully trained in the right direction.
