### ISSUE TITLE
custom network issue

### ISSUE THREAD

**Issue by jyan-R** [facebookresearch/Pearl#75]
When using SAC, if I set actor net to customize network inherit from `DynamicActionActorNetwork`, the following code will lead to incorrect network shape for the actor.

https://github.com/facebookresearch/Pearl/blob/f5b09450e9e9f3734742871167597f469dfb7503/pearl/policy_learners/sequential_decision_making/actor_critic_base.py#L113C1-L127C10

It maybe better to replace `is` with `issubclass()`

**Comment by rodrigodesalvobraz** [comment]
Good catch, thank you. We are following your suggestion. The change should be reflected to GitHub today or tomorrow.
