### ISSUE TITLE
TorchRL Vs Pearl: What's the difference & when to use one?

### ISSUE THREAD

**Issue by deependujha** [facebookresearch/Pearl#78]
I mostly use pytorch for my deep learning models, and I recently started learning reinforcement learning.

I came across TorchRL & Pearl. I couldn't find a brief answer on what's the difference between the two and when to use which one.

**Comment by rodrigodesalvobraz** [comment]
Hi. TorchRL and Pearl have been developed independently inside Meta. TorchRL is more integrated with the PyTorch environment, and has been around for longer than Pearl. Pearl has been developed with a target of being increasingly better integrated with production systems, and to provide easy customization for things like history summarization and safety modules. However, TorchRL can certainly also be used in production cases.
I don't think there is a clear cut answer as to when to use one or the other. I would advise you to look at the tutorials for one and the other and see which one has a style that agrees more with your preferences and use cases.
