### ISSUE TITLE
Link to project site in README broken?

### ISSUE THREAD

**Issue by KristianHolsheimer** [facebookresearch/Pearl#8]
Yay first bug!

I'm interested to find out more about pearl. I landed on the README from LinkedIn and clicked the first link to the "official website", which gets me to a page for which I don't have permissions to view (I think).

Congrats on the launch 🎉

**Comment by BillMatrix** [comment]
README fix is landing already. Should be fixed in an hour or so. Thanks for bringing this to our attention!

**Comment by BillMatrix** [comment]
Fixed now. Thanks for bringing this to our attention!
