### ISSUE TITLE
Suggestion: Add linters, formatters, and type checkers to ensure code quality and coding style consistency

### ISSUE THREAD

**Issue by shenxiangzhuang** [facebookresearch/Pearl#9]
https://github.com/facebookresearch/Pearl/blob/7cb515ae823cefa7e8adb2c92eb7eade943fc79e/CONTRIBUTING.md?plain=1#L18

https://github.com/facebookresearch/Pearl/blob/7cb515ae823cefa7e8adb2c92eb7eade943fc79e/CONTRIBUTING.md?plain=1#L35-L37

With the contributing suggestions here, it's will be better if we can add some linters&formatter(ruff, black, isort, flake8) and type checkers(mypy) in the ci to check them automatically.

**Comment by BillMatrix** [comment]
Thanks for your suggestion. Our next version will have CI included so stay tuned.
